// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChatsColumns holds the columns for the "chats" table.
	ChatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sender_id", Type: field.TypeInt},
		{Name: "receiver_id", Type: field.TypeInt},
		{Name: "message", Type: field.TypeString},
		{Name: "sent_at", Type: field.TypeTime},
	}
	// ChatsTable holds the schema information for the "chats" table.
	ChatsTable = &schema.Table{
		Name:       "chats",
		Columns:    ChatsColumns,
		PrimaryKey: []*schema.Column{ChatsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserRelationsColumns holds the columns for the "user_relations" table.
	UserRelationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id_1", Type: field.TypeInt},
		{Name: "user_id_2", Type: field.TypeInt},
	}
	// UserRelationsTable holds the schema information for the "user_relations" table.
	UserRelationsTable = &schema.Table{
		Name:       "user_relations",
		Columns:    UserRelationsColumns,
		PrimaryKey: []*schema.Column{UserRelationsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChatsTable,
		UsersTable,
		UserRelationsTable,
	}
)

func init() {
}
