// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChatsColumns holds the columns for the "chats" table.
	ChatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sender_id", Type: field.TypeInt},
		{Name: "receiver_id", Type: field.TypeInt},
		{Name: "message", Type: field.TypeString},
		{Name: "sent_at", Type: field.TypeTime},
		{Name: "user_sent_messages", Type: field.TypeInt, Nullable: true},
		{Name: "user_received_messages", Type: field.TypeInt, Nullable: true},
	}
	// ChatsTable holds the schema information for the "chats" table.
	ChatsTable = &schema.Table{
		Name:       "chats",
		Columns:    ChatsColumns,
		PrimaryKey: []*schema.Column{ChatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chats_users_sent_messages",
				Columns:    []*schema.Column{ChatsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "chats_users_received_messages",
				Columns:    []*schema.Column{ChatsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserRelationsColumns holds the columns for the "user_relations" table.
	UserRelationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id_1", Type: field.TypeInt},
		{Name: "user_id_2", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_user_relations_1", Type: field.TypeInt, Nullable: true},
		{Name: "user_user_relations_2", Type: field.TypeInt, Nullable: true},
	}
	// UserRelationsTable holds the schema information for the "user_relations" table.
	UserRelationsTable = &schema.Table{
		Name:       "user_relations",
		Columns:    UserRelationsColumns,
		PrimaryKey: []*schema.Column{UserRelationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_relations_users_user_relations_1",
				Columns:    []*schema.Column{UserRelationsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "user_relations_users_user_relations_2",
				Columns:    []*schema.Column{UserRelationsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChatsTable,
		UsersTable,
		UserRelationsTable,
	}
)

func init() {
	ChatsTable.ForeignKeys[0].RefTable = UsersTable
	ChatsTable.ForeignKeys[1].RefTable = UsersTable
	UserRelationsTable.ForeignKeys[0].RefTable = UsersTable
	UserRelationsTable.ForeignKeys[1].RefTable = UsersTable
}
