// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Real-Time-Chat/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// UserRelations1 holds the value of the user_relations_1 edge.
	UserRelations1 []*UserRelation `json:"user_relations_1,omitempty"`
	// UserRelations2 holds the value of the user_relations_2 edge.
	UserRelations2 []*UserRelation `json:"user_relations_2,omitempty"`
	// SentMessages holds the value of the sent_messages edge.
	SentMessages []*Chat `json:"sent_messages,omitempty"`
	// ReceivedMessages holds the value of the received_messages edge.
	ReceivedMessages []*Chat `json:"received_messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserRelations1OrErr returns the UserRelations1 value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserRelations1OrErr() ([]*UserRelation, error) {
	if e.loadedTypes[0] {
		return e.UserRelations1, nil
	}
	return nil, &NotLoadedError{edge: "user_relations_1"}
}

// UserRelations2OrErr returns the UserRelations2 value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserRelations2OrErr() ([]*UserRelation, error) {
	if e.loadedTypes[1] {
		return e.UserRelations2, nil
	}
	return nil, &NotLoadedError{edge: "user_relations_2"}
}

// SentMessagesOrErr returns the SentMessages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SentMessagesOrErr() ([]*Chat, error) {
	if e.loadedTypes[2] {
		return e.SentMessages, nil
	}
	return nil, &NotLoadedError{edge: "sent_messages"}
}

// ReceivedMessagesOrErr returns the ReceivedMessages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ReceivedMessagesOrErr() ([]*Chat, error) {
	if e.loadedTypes[3] {
		return e.ReceivedMessages, nil
	}
	return nil, &NotLoadedError{edge: "received_messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldEmail, user.FieldPasswordHash:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				u.Username = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				u.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				u.PasswordHash = value.String
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryUserRelations1 queries the "user_relations_1" edge of the User entity.
func (u *User) QueryUserRelations1() *UserRelationQuery {
	return NewUserClient(u.config).QueryUserRelations1(u)
}

// QueryUserRelations2 queries the "user_relations_2" edge of the User entity.
func (u *User) QueryUserRelations2() *UserRelationQuery {
	return NewUserClient(u.config).QueryUserRelations2(u)
}

// QuerySentMessages queries the "sent_messages" edge of the User entity.
func (u *User) QuerySentMessages() *ChatQuery {
	return NewUserClient(u.config).QuerySentMessages(u)
}

// QueryReceivedMessages queries the "received_messages" edge of the User entity.
func (u *User) QueryReceivedMessages() *ChatQuery {
	return NewUserClient(u.config).QueryReceivedMessages(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("username=")
	builder.WriteString(u.Username)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(u.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(u.PasswordHash)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
