// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Real-Time-Chat/ent/predicate"
	"Real-Time-Chat/ent/user"
	"Real-Time-Chat/ent/userrelation"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserRelationQuery is the builder for querying UserRelation entities.
type UserRelationQuery struct {
	config
	ctx        *QueryContext
	order      []userrelation.OrderOption
	inters     []Interceptor
	predicates []predicate.UserRelation
	withUser1  *UserQuery
	withUser2  *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserRelationQuery builder.
func (urq *UserRelationQuery) Where(ps ...predicate.UserRelation) *UserRelationQuery {
	urq.predicates = append(urq.predicates, ps...)
	return urq
}

// Limit the number of records to be returned by this query.
func (urq *UserRelationQuery) Limit(limit int) *UserRelationQuery {
	urq.ctx.Limit = &limit
	return urq
}

// Offset to start from.
func (urq *UserRelationQuery) Offset(offset int) *UserRelationQuery {
	urq.ctx.Offset = &offset
	return urq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (urq *UserRelationQuery) Unique(unique bool) *UserRelationQuery {
	urq.ctx.Unique = &unique
	return urq
}

// Order specifies how the records should be ordered.
func (urq *UserRelationQuery) Order(o ...userrelation.OrderOption) *UserRelationQuery {
	urq.order = append(urq.order, o...)
	return urq
}

// QueryUser1 chains the current query on the "user1" edge.
func (urq *UserRelationQuery) QueryUser1() *UserQuery {
	query := (&UserClient{config: urq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := urq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := urq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userrelation.Table, userrelation.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userrelation.User1Table, userrelation.User1Column),
		)
		fromU = sqlgraph.SetNeighbors(urq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser2 chains the current query on the "user2" edge.
func (urq *UserRelationQuery) QueryUser2() *UserQuery {
	query := (&UserClient{config: urq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := urq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := urq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userrelation.Table, userrelation.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userrelation.User2Table, userrelation.User2Column),
		)
		fromU = sqlgraph.SetNeighbors(urq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserRelation entity from the query.
// Returns a *NotFoundError when no UserRelation was found.
func (urq *UserRelationQuery) First(ctx context.Context) (*UserRelation, error) {
	nodes, err := urq.Limit(1).All(setContextOp(ctx, urq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userrelation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (urq *UserRelationQuery) FirstX(ctx context.Context) *UserRelation {
	node, err := urq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserRelation ID from the query.
// Returns a *NotFoundError when no UserRelation ID was found.
func (urq *UserRelationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = urq.Limit(1).IDs(setContextOp(ctx, urq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userrelation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (urq *UserRelationQuery) FirstIDX(ctx context.Context) int {
	id, err := urq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserRelation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserRelation entity is found.
// Returns a *NotFoundError when no UserRelation entities are found.
func (urq *UserRelationQuery) Only(ctx context.Context) (*UserRelation, error) {
	nodes, err := urq.Limit(2).All(setContextOp(ctx, urq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userrelation.Label}
	default:
		return nil, &NotSingularError{userrelation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (urq *UserRelationQuery) OnlyX(ctx context.Context) *UserRelation {
	node, err := urq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserRelation ID in the query.
// Returns a *NotSingularError when more than one UserRelation ID is found.
// Returns a *NotFoundError when no entities are found.
func (urq *UserRelationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = urq.Limit(2).IDs(setContextOp(ctx, urq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userrelation.Label}
	default:
		err = &NotSingularError{userrelation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (urq *UserRelationQuery) OnlyIDX(ctx context.Context) int {
	id, err := urq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserRelations.
func (urq *UserRelationQuery) All(ctx context.Context) ([]*UserRelation, error) {
	ctx = setContextOp(ctx, urq.ctx, "All")
	if err := urq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserRelation, *UserRelationQuery]()
	return withInterceptors[[]*UserRelation](ctx, urq, qr, urq.inters)
}

// AllX is like All, but panics if an error occurs.
func (urq *UserRelationQuery) AllX(ctx context.Context) []*UserRelation {
	nodes, err := urq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserRelation IDs.
func (urq *UserRelationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if urq.ctx.Unique == nil && urq.path != nil {
		urq.Unique(true)
	}
	ctx = setContextOp(ctx, urq.ctx, "IDs")
	if err = urq.Select(userrelation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (urq *UserRelationQuery) IDsX(ctx context.Context) []int {
	ids, err := urq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (urq *UserRelationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, urq.ctx, "Count")
	if err := urq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, urq, querierCount[*UserRelationQuery](), urq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (urq *UserRelationQuery) CountX(ctx context.Context) int {
	count, err := urq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (urq *UserRelationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, urq.ctx, "Exist")
	switch _, err := urq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (urq *UserRelationQuery) ExistX(ctx context.Context) bool {
	exist, err := urq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserRelationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (urq *UserRelationQuery) Clone() *UserRelationQuery {
	if urq == nil {
		return nil
	}
	return &UserRelationQuery{
		config:     urq.config,
		ctx:        urq.ctx.Clone(),
		order:      append([]userrelation.OrderOption{}, urq.order...),
		inters:     append([]Interceptor{}, urq.inters...),
		predicates: append([]predicate.UserRelation{}, urq.predicates...),
		withUser1:  urq.withUser1.Clone(),
		withUser2:  urq.withUser2.Clone(),
		// clone intermediate query.
		sql:  urq.sql.Clone(),
		path: urq.path,
	}
}

// WithUser1 tells the query-builder to eager-load the nodes that are connected to
// the "user1" edge. The optional arguments are used to configure the query builder of the edge.
func (urq *UserRelationQuery) WithUser1(opts ...func(*UserQuery)) *UserRelationQuery {
	query := (&UserClient{config: urq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	urq.withUser1 = query
	return urq
}

// WithUser2 tells the query-builder to eager-load the nodes that are connected to
// the "user2" edge. The optional arguments are used to configure the query builder of the edge.
func (urq *UserRelationQuery) WithUser2(opts ...func(*UserQuery)) *UserRelationQuery {
	query := (&UserClient{config: urq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	urq.withUser2 = query
	return urq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID1 int `json:"user_id_1,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserRelation.Query().
//		GroupBy(userrelation.FieldUserID1).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (urq *UserRelationQuery) GroupBy(field string, fields ...string) *UserRelationGroupBy {
	urq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserRelationGroupBy{build: urq}
	grbuild.flds = &urq.ctx.Fields
	grbuild.label = userrelation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID1 int `json:"user_id_1,omitempty"`
//	}
//
//	client.UserRelation.Query().
//		Select(userrelation.FieldUserID1).
//		Scan(ctx, &v)
func (urq *UserRelationQuery) Select(fields ...string) *UserRelationSelect {
	urq.ctx.Fields = append(urq.ctx.Fields, fields...)
	sbuild := &UserRelationSelect{UserRelationQuery: urq}
	sbuild.label = userrelation.Label
	sbuild.flds, sbuild.scan = &urq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserRelationSelect configured with the given aggregations.
func (urq *UserRelationQuery) Aggregate(fns ...AggregateFunc) *UserRelationSelect {
	return urq.Select().Aggregate(fns...)
}

func (urq *UserRelationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range urq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, urq); err != nil {
				return err
			}
		}
	}
	for _, f := range urq.ctx.Fields {
		if !userrelation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if urq.path != nil {
		prev, err := urq.path(ctx)
		if err != nil {
			return err
		}
		urq.sql = prev
	}
	return nil
}

func (urq *UserRelationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserRelation, error) {
	var (
		nodes       = []*UserRelation{}
		withFKs     = urq.withFKs
		_spec       = urq.querySpec()
		loadedTypes = [2]bool{
			urq.withUser1 != nil,
			urq.withUser2 != nil,
		}
	)
	if urq.withUser1 != nil || urq.withUser2 != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userrelation.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserRelation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserRelation{config: urq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, urq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := urq.withUser1; query != nil {
		if err := urq.loadUser1(ctx, query, nodes, nil,
			func(n *UserRelation, e *User) { n.Edges.User1 = e }); err != nil {
			return nil, err
		}
	}
	if query := urq.withUser2; query != nil {
		if err := urq.loadUser2(ctx, query, nodes, nil,
			func(n *UserRelation, e *User) { n.Edges.User2 = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (urq *UserRelationQuery) loadUser1(ctx context.Context, query *UserQuery, nodes []*UserRelation, init func(*UserRelation), assign func(*UserRelation, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserRelation)
	for i := range nodes {
		if nodes[i].user_user_relations_1 == nil {
			continue
		}
		fk := *nodes[i].user_user_relations_1
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_user_relations_1" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (urq *UserRelationQuery) loadUser2(ctx context.Context, query *UserQuery, nodes []*UserRelation, init func(*UserRelation), assign func(*UserRelation, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserRelation)
	for i := range nodes {
		if nodes[i].user_user_relations_2 == nil {
			continue
		}
		fk := *nodes[i].user_user_relations_2
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_user_relations_2" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (urq *UserRelationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := urq.querySpec()
	_spec.Node.Columns = urq.ctx.Fields
	if len(urq.ctx.Fields) > 0 {
		_spec.Unique = urq.ctx.Unique != nil && *urq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, urq.driver, _spec)
}

func (urq *UserRelationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userrelation.Table, userrelation.Columns, sqlgraph.NewFieldSpec(userrelation.FieldID, field.TypeInt))
	_spec.From = urq.sql
	if unique := urq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if urq.path != nil {
		_spec.Unique = true
	}
	if fields := urq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userrelation.FieldID)
		for i := range fields {
			if fields[i] != userrelation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := urq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := urq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := urq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := urq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (urq *UserRelationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(urq.driver.Dialect())
	t1 := builder.Table(userrelation.Table)
	columns := urq.ctx.Fields
	if len(columns) == 0 {
		columns = userrelation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if urq.sql != nil {
		selector = urq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if urq.ctx.Unique != nil && *urq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range urq.predicates {
		p(selector)
	}
	for _, p := range urq.order {
		p(selector)
	}
	if offset := urq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := urq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserRelationGroupBy is the group-by builder for UserRelation entities.
type UserRelationGroupBy struct {
	selector
	build *UserRelationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (urgb *UserRelationGroupBy) Aggregate(fns ...AggregateFunc) *UserRelationGroupBy {
	urgb.fns = append(urgb.fns, fns...)
	return urgb
}

// Scan applies the selector query and scans the result into the given value.
func (urgb *UserRelationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, urgb.build.ctx, "GroupBy")
	if err := urgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserRelationQuery, *UserRelationGroupBy](ctx, urgb.build, urgb, urgb.build.inters, v)
}

func (urgb *UserRelationGroupBy) sqlScan(ctx context.Context, root *UserRelationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(urgb.fns))
	for _, fn := range urgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*urgb.flds)+len(urgb.fns))
		for _, f := range *urgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*urgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := urgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserRelationSelect is the builder for selecting fields of UserRelation entities.
type UserRelationSelect struct {
	*UserRelationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (urs *UserRelationSelect) Aggregate(fns ...AggregateFunc) *UserRelationSelect {
	urs.fns = append(urs.fns, fns...)
	return urs
}

// Scan applies the selector query and scans the result into the given value.
func (urs *UserRelationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, urs.ctx, "Select")
	if err := urs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserRelationQuery, *UserRelationSelect](ctx, urs.UserRelationQuery, urs, urs.inters, v)
}

func (urs *UserRelationSelect) sqlScan(ctx context.Context, root *UserRelationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(urs.fns))
	for _, fn := range urs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*urs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := urs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
