// Code generated by ent, DO NOT EDIT.

package userrelations

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the userrelations type in the database.
	Label = "user_relations"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID1 holds the string denoting the user_id_1 field in the database.
	FieldUserID1 = "user_id_1"
	// FieldUserID2 holds the string denoting the user_id_2 field in the database.
	FieldUserID2 = "user_id_2"
	// Table holds the table name of the userrelations in the database.
	Table = "user_relations"
)

// Columns holds all SQL columns for userrelations fields.
var Columns = []string{
	FieldID,
	FieldUserID1,
	FieldUserID2,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UserRelations queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID1 orders the results by the user_id_1 field.
func ByUserID1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID1, opts...).ToFunc()
}

// ByUserID2 orders the results by the user_id_2 field.
func ByUserID2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID2, opts...).ToFunc()
}
